onlyBuiltDependencies:
  - "@fortawesome/fontawesome-common-types"
  - "@fortawesome/fontawesome-svg-core"
  - "@fortawesome/free-brands-svg-icons"
  - "@fortawesome/free-solid-svg-icons"
  - core-js
  - core-js-pure
  - protobufjs
  - sharp
  - styled-components
